### ISSUE TITLE
add contributor agreement to site

### ISSUE THREAD

**Issue by drewda** [transitland/www-transit-land#132]
the final text is at https://github.com/mapzen/transitland-internal/issues/1#issuecomment-173364687

**Comment by drewda** [comment]
@hanbyul-here https://transit.land/an-open-project/contributor-agreement.html

**Comment by hanbyul-here** [comment]
I pushed these pages to my branch https://github.com/transitland/www-transit-land/tree/hanb/agreement-page would you review some hierarchy of lists? (for both pages) @drewda

**Comment by drewda** [comment]
looks great. thanks, @hanbyul-here
