### ISSUE TITLE
Documentation for API doesn't specify domain

### ISSUE THREAD

**Issue by meghanhade** [transitland/www-transit-land#156]
/documentation/datastore/api-endpoints.html doesn't explain what domain should be used (transit.land)

**Comment by rmglennon** [comment]
good point @meghanhade. I thought it jumped in a bit too much on that page, too, so this fix gave the opportunity to add some context. How about this?

To query the Transitland Datastore API, use the base URL of `https://transit.land/`, appended with the endpoint information below. For example, to find routes operated by the San Francisco Municipal Transportation Agency (SFMTA), you can use this query: `https://transit.land/api/v1/routes?operated_by=o-9q8y-sfmta`.

The following endpoints are available in Transitland Datatstore API.

(then the table)

**Comment by meghanhade** [comment]
That looks great, @rmglennon!
