### ISSUE TITLE
chrome for demos or a project gallery

### ISSUE THREAD

**Issue by drewda** [transitland/www-transit-land#171]
@souperneon @hanbyul-here we'd like to feature @doublestranded 's new demo somewhere on Transitland

Right now it's at http://transitland.github.io/route-spotter/

Two ideas:

- Put some chrome around the demo that has a Transitland logo and a link to transit.land for more information
- Embed it in a project or apps "gallery" on transit.land as an iframe

What do you two think?

**Comment by hanbyul-here** [comment]
is this long term one? If it is not, wouldn't it better to feature these demos inside of blog together?

**Comment by drewda** [comment]
O.K., sounds good to just feature it in the blog for now, as an iframe (We can save a gallery of apps/projects for the future.)

@hanbyul-here could you add a Transitland logo, a "Route Spotter" header, and a link to "read more" at https://transitland in the top of https://github.com/transitland/route-spotter/blob/master/index.html ?

**Comment by drewda** [comment]
I think we should create "gallery" of projects on transit.land at some point, but that can wait 'til the future.
