### ISSUE TITLE
intro/overview tutorial

### ISSUE THREAD

**Issue by drewda** [transitland/www-transit-land#217]

**Comment by kkowalsky** [comment]
I'm going to be working on this, following the workshop template provided.

**Comment by drewda** [comment]
Materials from Transitland workshop at last year's SOTM-US that @meghanhade, @irees, and I taught:
- notes: https://docs.google.com/document/d/1VHHT3I0owc_S5ifgcY062tiV4fkTnxs9HVbX5CKdFys/edit
- abstract: https://docs.google.com/document/d/1MCV8FYWz_pVd-mgE8h64oOLYEFx9h9e1ST2CWqgq7b0/edit
- transcript: https://mapzen-assets.s3.amazonaws.com/images/state-of-the-map-2015-wrapup/sotmus2015_Mapzen_transcripts.html#drew-meghan-ian
