### ISSUE TITLE
Transitland Datastore API image broken

### ISSUE THREAD

**Issue by kkowalsky** [transitland/www-transit-land#236]
Just noticed that this blog has a broken image: https://transit.land/news/2015/11/13/schedule-api.html

looks like the images folder for this post doesn't have the image the broken link is referring to (Visualizing frequent transit networks).

**Comment by drewda** [comment]
Thanks for noticing, @kkowalsky! Must have gotten lost when we copied that post over from https://mapzen.com/blog/the-transit-dimension-transit-land-schedule-api/
