### ISSUE TITLE
one_stopid catch alse holiday trips

### ISSUE THREAD

**Issue by piersoft** [transitland/www-transit-land#245]
when i use:
https://transit.land/api/v1/schedule_stop_pairs?destination_onestop_id=s-srhvmp4sep-nocco2&origin_departure_between=09:00,09:30

there are 2 route: 16 and 24. But 16 is a route only for Sunday.

how can i filter only today's routes at specific hour in specific stop_id?
thanks

**Comment by irees** [comment]
hi @piersoft 

You can use the "date" query parameter to filter for schedules on a specific day --

https://transit.land/api/v1/schedule_stop_pairs?destination_onestop_id=s-srhvmp4sep-nocco2&origin_departure_between=09:00,09:30&date=2016-10-10

Setting it to 2016-10-10 (Monday) shows only the 24.

(Note: I imported the most recent version of the feed a moment ago)

**Comment by irees** [comment]
@piersoft -- One quick note. This is the repo for our blog. General questions and issues might find a broader audience in https://github.com/transitland/transitland/issues
