### ISSUE TITLE
broken playground links on homepage

### ISSUE THREAD

**Issue by meetar** [transitland/www-transit-land#250]
The two `a` tags in this section:

https://github.com/transitland/www-transit-land/blob/master/index.html#L86-L93

wrapping the playground section header image and the text "Give it a try!" …purport to link to the playground (they're in the code as `{{site.playground_url}}`).

However those links on https://transit.land/ currently point to the homepage instead.

That variable is apparently set here, and looks correct: https://github.com/transitland/playground/blob/master/_plugins/environment_variables.rb#L12

So maybe those variables aren't being referenced? I do notice that the other links in that section aren't referencing environment variables at all, but are hard-coded with relative urls: `/documentation` and `/participate`

**Comment by drewda** [comment]
Thanks for catching this, @meetar!
