### ISSUE TITLE
Update Playground's "Show Ops by Name" workflow

### ISSUE THREAD

**Issue by kuanb** [transitland/www-transit-land#291]
Loc: https://transit.land/playground/

When you opt for the following workflow:
![image](https://user-images.githubusercontent.com/6053396/34057058-609b0f86-e18a-11e7-9b92-e2d537ae3121.png)

The following query is run:
```
https://transit.land/api/v1/operators.json?per_page=5000
```

This results, inevitably, in a gateway timeout error. The result of this is errors (or unpopulated dropdown menus) after the "IN" prompt:
![image](https://user-images.githubusercontent.com/6053396/34057116-946186ec-e18a-11e7-8d3e-ec48a11eecbe.png)

I don't remember what the intention of this workflow was, but I assume (or it would be nice) to have a string query, wherein a user can just look for operators that include a certain name (e.g. "muncie" for Muncie, Indiana).

At the very least, dropping the `per_page` to something less than 5000 will help avoid timeouts.

**Comment by stevevance** [comment]
I think there might be another issue to remove Playground from the site and point people to Mobility Explorer.

**Comment by drewda** [comment]
You're both right. Playground has visible issues. We've deprecated the code (https://github.com/transitland/playground/blob/master/README.md#transitland-playground) but have yet to complete the website changes to emphasize Mapzen Mobility Explorer and other clients: https://github.com/transitland/transitland/issues/199
