### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by taokos** [transitland/www-transit-land#293]
Need to get all stop pairs by "operator_onestop_id" but we can't get this information by link: https://api.transit.land/api/v1/schedule_stop_pairs?offset=5784000&per_page=1&operator_onestop_id=o-dr5r-nyct because when "offset option" is more 5784000 we get Time-out page.

Do exist any way to get this information?

**Comment by drewda** [comment]
@taokos using `offset` can be an expensive query within the database in certain situations. Try using the `sort_min_id` parameter instead.
